---
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux

archives:
  - formats: [binary]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
    name_template: "{{ .ProjectName }}-checksums.txt"
